### PR TITLE
1.4.5

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
@fiorix, how about 1.4.5?

### CODE REVIEW

**Comment by fiorix** [comment]
👍

**Comment by IlyaSkriblovsky** [comment]
Thanks! Could you also upload 1.4.5 to PyPI, please?

**Comment by IlyaSkriblovsky** [comment]
(a humble reminder to release the v1.4.5, please :) )

**Comment by fiorix** [comment]
Heya, my bad. Lost track of things. Busy week !

**Comment by fiorix** [comment]
wtf is going on with pypi? i haven't used it in a while but apparently they changed the api and now it tells me to upgrade but the page it links to doesn't say much... what am i missing here?

**Comment by IlyaSkriblovsky** [comment]
ashamed to say, but I haven't published anything to pypi, so can't help you with it :(

**Comment by IlyaSkriblovsky** [comment]
@fiorix, hi, did you managed the pypi issue? By the way, I've added 1.4.6 release in #123 fixing sentinel+auth issue :)  Could you please try to upload it?

**Pull request merged**
