### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by jeethu**
I happened to run `trial` with `--coverage`. I've added a few tests to cover some of the untested code that I found.

### CODE REVIEW

**Comment by fiorix** [comment]
Great, thanks!

**Comment by fiorix** [comment]
This failed on Travis-ci but is due to a network connection error for downloading Twisted. I'm re-running the test now.

**Comment by jeethu** [comment]
Looks like it failed again, with the same network error while downloading Twisted for the Python 2.6 tests. Could you run it again?

**Comment by fiorix** [comment]
Yes, still failing. Doing it again.

**Pull request merged**
