### PR TITLE
1.4.2

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
Can we have a 1.4.2 with pipelining support? This would simplify deployment for me.

### CODE REVIEW

**Comment by fiorix** [comment]
Absolutely. I would appreciate if you could add a `CONTRIBUTORS` file to this PR.
Here's a template:

```
# This is the official list of txredisapi contributors for copyright purposes.
#
# Names should be added to this file as
#	Name or Organization <email address>
#
# The email address is not required for organizations.
#
# Please keep the list sorted.

```

Can generate the list:

```git shortlog -se | awk '{print $2 " " $3 " " $4}'```

and do appropriate cleanups.

**Comment by IlyaSkriblovsky** [comment]
Do you prefer names with a list of contributions under each, or simply list of names [like in txmongo](https://github.com/mongodb/mongo-python-driver/blob/master/doc/contributors.rst)?

**Comment by fiorix** [comment]
The simpler the better, IMO.

**Comment by IlyaSkriblovsky** [comment]
Merging?

**Comment by fiorix** [comment]
:+1:

**Comment by IlyaSkriblovsky** [comment]
Could you please upload it to PyPI too?

**Comment by IlyaSkriblovsky** [comment]
knock-knock :)

**Comment by fiorix** [comment]
Done

**Comment by IlyaSkriblovsky** [comment]
:pray:

**Pull request merged**
