### PR TITLE
Python 3.5 support

### PR DESCRIPTION
**Pull request by jeethu**
I had to remove support for Python 2.6 and add a dependency on [six](https://pypi.python.org/pypi/six).

### CODE REVIEW

**Comment by jeethu** [comment]
The build failure seems to be a travis-ci issue. I've got the branch [passing](https://travis-ci.org/jeethu/txredisapi/builds/94222810) all tests on my fork.

@fiorix could you issue a re-test on travis?

**Comment by fiorix** [comment]
I did re-issue it a couple times, travis was failing every single time randomly. Let me do it once more.

**Comment by jeethu** [comment]
Looks like it's still failing. Seems like the all four permutations of the tests are run in parallel by travis and only one of them passes because they all share the same redis server.

**Comment by fiorix** [comment]
yeah still failing... perhaps we can do something to accommodate the tests better for travis?

**Comment by jeethu** [comment]
Reverted back to old style builds on travis and the tests are passing now.

**Comment by jeethu** [comment]
@fiorix Another way to fix this would be to [limit](https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Builds) concurrent jobs to 1 on travis.

**Comment by fiorix** [comment]
It passed while I was configuring the limit. It is limited to 1 now anyway.

**Pull request merged**
