### PR TITLE
Remove pipeline connections from the pool until they are complete.

### PR DESCRIPTION
**Pull request by steiza**
Modeled after how transactions are handled.

When a pipeline starts it was not getting removed from the
ConnectionPool, and so if you make enough requests to cycle through your
ConnectionPool before the pipeline executes you could end up sticking
non-pipeline requests in a pipeline unintentionally.

### CODE REVIEW

**Comment by dpkp** [comment]
can you take a stab at writing a test ?

**Comment by steiza** [comment]
Sure, sorry for the delay! With this extra test here's what I get on my local machine:

```
$ nosetests tests/test_pipelining.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.032s

OK
```

... and here's what happens on the version of txredisapi before my path:
```
...FE....
======================================================================
ERROR: test_ConnectionPool_managed_correctly
----------------------------------------------------------------------
DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class 'twisted.internet.tcp.Client'> to ('localhost', 6379) at 7f6574a80e90>

======================================================================
FAIL: test_ConnectionPool_managed_correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/home/steiza/cloud/code/txredisapi/tests/test_pipelining.py", line 124, in test_ConnectionPool_managed_correctly
    self.assertEqual(len(results), 1)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
FailTest: not equal:
a = 2
b = 1


----------------------------------------------------------------------
Ran 8 tests in 0.035s

FAILED (errors=1, failures=1)
```

**Comment by etataurov** [comment]
Have you seen my PR #69 ? Seems like we did the same thing

**Comment by steiza** [comment]
Yeah, I don't care which pull request gets used, but it would be really good to fix pipelining and connection pools either way... @etataurov it looks like you might need to pull in changes from master and resolve conflicts on your branch?

**Comment by sofuture** [comment]
@fiorix @dpkp ping :bell:

**Comment by fiorix** [comment]
I'm happy to do whatever you guys agree to :)

**Comment by sofuture** [comment]
@fiorix I vote for merging this, but that's just 'cause I work with @steiza :wink: 

@steiza @etataurov: sounds like it's up to y'all to pick a PR

**Comment by etataurov** [comment]
I'm OK with every option :smile: we could flip a coin. or just merge this one, because it's more active

**Comment by fiorix** [comment]
Done! :)

**Pull request merged**
