### PR TITLE
Extended Python version support

### PR DESCRIPTION
**Pull request by tobixx**
let's not talk about which version but about the extended user base support ;-)

### CODE REVIEW

**Comment by IlyaSkriblovsky** [comment]
I don't mind adding 2.6 support if it doesn't hurt readability and doesn't add nasty compatibility tricks.
Your patch looks pretty clean and simple, so if would help any nonzero number of people, I'm ok with it :)

But since compatibility is also an organizational question lets hear from @fiorix.

Could you also add 2.6 as supported version to setup.py? (btw, 3.x should also be added there but this is a matter of another PR)

**Comment by fiorix** [comment]
LGTM 👍

**Comment by IlyaSkriblovsky** [comment]
Thanks!

**Comment by tobixx** [comment]
Thank you!

**Pull request merged**
