### PR TITLE
Fix reply timeout

### PR DESCRIPTION
**Pull request by jjappi**

### CODE REVIEW

**Comment by IlyaSkriblovsky** [comment]
Hi! You are right that current timeout handling is broken. It is effectively disabled since we never call `setTimeout`.

But I think your fix needs a bit more to be ideal:
- Please add `setTimeout(None)` to `connectionLost`. Your `test_connection_lost` doesn't fails with `Reactor was unclean` only because you monkey-patch `callLater`. In real life `setTimeout` will leak delayed call if it is not cancelled in `connectionLost`

- `resetTimeout` doesn't cancels watchdog timer, it only reschedules it to `timeOut` seconds from now. So if we issue a command, receive a reply and then connection will be idle for `timeOut` seconds, watchdog timer will fire and will close the connection. I don't think this is what we want. Timeout should be disabled if we received responses to all commands that we issued. This can be done by adding something like this to the end of `replyReceived`:
```python
if not self.replyQueue.waiting:
    self.setTimeout(None)
```

- calling `setTimeout` multiple times with same argument is effectively the same than calling `resetTimeout`: it just calls [`self.__timeoutCall.reset(period)`](http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.2.0/twisted/protocols/policies.py#L721). So, each command we send thru connection will reschedule watchdog timer and if we send commands regularly, timeout will never fire even we are not receiving any replies from Redis.

**Comment by jjappi** [comment]
Yes you are right, TimeoutMixin is intended for server side protocol handling. And this whole timeout handling is much more complicated than it first looked. I'm afraid I don't have time nor deep enough knowledge of the code (or Twisted itself) at this time to have proper fix for it. I'll close this PR and create an issue instead.

**Comment by jjappi** [comment]
Created #101

**Comment by IlyaSkriblovsky** [comment]
Thanks!

**Pull request closed without merging**
